Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ContaCorrente_02.Controllers
{
    public class LoginController : Controller
    {
        // GET: Login
        public ActionResult Index()
        {

            return View();
        }
    }
}

Controllers/LoginsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ContaCorrente_02.DAL;
using ContaCorrente_02.Models;

namespace ContaCorrente_02.Controllers
{
    public class LoginsController : Controller
    {
        private ContaCorrente_02Context db = new ContaCorrente_02Context();

        // GET: Logins
        public ActionResult Index()
        {
            return View(db.Logins.ToList());
        }

        // GET: Logins/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Login login = db.Logins.Find(id);
            if (login == null)
            {
                return HttpNotFound();
            }
            return View(login);
        }

        // GET: Logins/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Logins/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Utilizador,Password")] Login login)
        {
            if (ModelState.IsValid)
            {
                db.Logins.Add(login);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(login);
        }

        // GET: Logins/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Login login = db.Logins.Find(id);
            if (login == null)
            {
                return HttpNotFound();
            }
            return View(login);
        }

        // POST: Logins/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Utilizador,Password")] Login login)
        {
            if (ModelState.IsValid)
            {
                db.Entry(login).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(login);
        }

        // GET: Logins/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Login login = db.Logins.Find(id);
            if (login == null)
            {
                return HttpNotFound();
            }
            return View(login);
        }

        // POST: Logins/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Login login = db.Logins.Find(id);
            db.Logins.Remove(login);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Controllers/LogoutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ContaCorrente_02.Controllers
{
    public class LogoutController : Controller
    {
        // GET: Logout
        public ActionResult Index()
        {
            return View();
        }
    }
}

Controllers/RR2Controller.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ContaCorrente_02.DAL;
using ContaCorrente_02.RR;

namespace ContaCorrente_02.Controllers
{
    public class RR2Controller : Controller
    {
        private RRClass obj = new RRClass();
        // GET: RR2Controller
        public ActionResult Index()
        {

            obj.RecolonizarTabelaClientes();
            obj.RecolonizarTabelaMovimentos();
            return View();

        }
    }

}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("| CC ASP  |", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                @Html.ActionLink("1-Clientes |", "Index", "Clientes", new { area = "" }, new { @class = "navbar-brand" })
                @Html.ActionLink("2-Movimentos |", "Index", "Movimentoes", new { area = "" }, new { @class = "navbar-brand" })
                @Html.ActionLink("3-Recolonizar |", "Index", "RR2", new { area = "" }, new { @class = "navbar-brand" })
                @Html.ActionLink("4.1-Drop1 |", "Index", "ClientesMovimentos", new { area = "" }, new { @class = "navbar-brand" })
                @Html.ActionLink("Entrar |", "Index", "Login", new { area = "" }, new { @class = "navbar-brand" })
                @Html.ActionLink("Criar Utilizador |", "Index", "Logins", new { area = "" }, new { @class = "navbar-brand" })
                @Html.ActionLink("Sair |", "Index", "Logout", new { area = "" }, new { @class = "navbar-brand" })


            </div>
            @*<div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li>@Html.ActionLink("Home", "Index", "Home")</li>
                <li>@Html.ActionLink("About", "About", "Home")</li>
                <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
            </ul>
        </div>*@




            @*Tentativa de colocar o dropdown*@

            @*<li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">A..D<b class="caret"></b></a>

                <ul class="dropdown-menu">
                    <li>@Html.ActionLink(" [A] ", "Index", "A", new { area = "" }, new { @class = "", @title = "Drop com 4 clubes / List<string>" })</li>
                    <li>@Html.ActionLink(" [B] ", "Index", "B", new { area = "" }, new { @class = "", @title = "Foreach / List<Equipa>" })</li>
                    <li>@Html.ActionLink(" [C] ", "Index", "C", new { area = "" }, new { @class = "", @title = "Drops para tabelas" })</li>
                    <li>@Html.ActionLink(" [D] ", "Index", "D", new { area = "" }, new { @class = "", @title = "Visualizar a PK a partir da seleção na drop" })</li>
                </ul>
            </li>*@


        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        
        <footer>
            <p>&copy; @DateTime.Now.Year - Domingos Ribeiro</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>